language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
    - luarocks
before_install:
  - luarocks install --local lpeg
  - "eval `luarocks path`" # execute the luarocks output - sets the paths for 'local' tree
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - test -f .gitmodules && (sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules && git submodule update --init --recursive) || true
git:
    submodules: false # Handle git submodules yourself

script: "./build.sh -l $LOVE -n $NAME `[[ -n $TRAVIS_TAG ]] && echo web`" # web only for tags
deploy:
  provider: releases
  skip_cleanup: true
### curl -u premysl.vyhnal@gmail.com --header 'x-github-otp: XXXXXX' -d '{"scopes":["public_repo"],"note":"XXX name XXX"}'   https://api.github.com/authorizations  
  api_key:
    # travis encrypt <token>
    secure: "sW+VprZNhYGNYXJXLJFLqguPRl7qxyuYzBT/Bmcg8TH9mrCm/0AmVvI50eICfNFrSRUvfKhfKMHOjGF2Yq19JhplWZe11+/vnN1X6AP86LubjYyDfMpl95yya7NLzKlQsNs7k3FXqHvE9jxu5Z9IpNy4hRie54f2JpWg3ni8JTP8JkfeNBxu5pW9OGKb2BzvVcRy15JE8Zro107KDtBHdlsNVHfDsCfBSaG2x5SViE15oxKMW3g+d+xGUGn8+MGpsZcig83KFktaM2+RPJ2Hcrxqy26ZW1qUID/6jn5ijuMLwe70PJFWjRf4em/WoNrC1rX6IAVm0AjuSjgqOiWKoCHtfLzXG8c0e2PjfihpzGGh3FgTiViaqH9bdnZwTa9gs/pcuNGxJuX/1fHluqhz8/78CXYMucVVTOc/zwXG54Jp4zTmEWDqhrzL29an6BizaqU0umzIYT/pbZ9zwHEDUzfZWu9nftQoOXhSxFkVu47E6Vy+SRviO+rhKyhJUxKFFYwaIwfSx59Dpgc1/c9ckPWSesjW57UBmwsBGrX+bdM/BNw1K8bfynHyQTMuQEZtfjZJpgU1+xraCevUZlmcuwdMv/4tRWa8gOiVnVaEOV8PDI6p0l1y95RAs3hjy4t/di8FtCvbDfVv6ik6fJLrKvEGjZnn2WoFbqyJoS+1yrs="
  file:
  - target/$NAME.love
  - target/$NAME-win.zip
  - target/$NAME-web.zip
  on:
    tags: true
    all_branches: true
after_success:
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh -l $LOVE -n $NAME deploy $TRAVIS_REPO_SLUG"
env:
  global:
  - NAME=forest
  - LOVE=11.3
  # travis encrypt GH_TOKEN=<token>
  - secure: "UpBpdXXHFbiCr4BYs8rMUGz9zTqBBQJg8fHpPiNoV6DMP+NZ+f0wYcZKGLrkzIulf7wLf1Q/i1FimtYiXnAAf2kdYxFFJcNOvHSmTr8xLYx0+guKx05kNZC0u2Vtka0KxcA2mT8d7UYSJHTkm7yOAguYqKN5j5e5ZiW056AyEWrfTzZ/MMdOVJdb9Ffmlj1CLeh8pMlLClxg6W1yGryH4+BTd4M+pPeSOJVTiiLhrNd3HmWc1hdETMqe0xutlT6PhjCbmtAXt+WL2dvD+qWy8Bq5YaG+F81IQQXMAV6KBwJ/2OCbPxoOLtXhH1KRcg9soj1IDLmezLDJfxb64dwTBYf49noWhESD+Rv9HuGuth65ELwFpEU6a91Pj7DwDeTdmCJXII8sa5B10x4RQozVDpjmQ4HghY3RLXau9JA7Zy7rsCVB7Mtc3u6aSG1ZM4u4SPkieSIwX2xzrt3dnEIpUbzTkEj+623IhamefBMOBMgItrh0TCc8DKnErfvkW3vfyQOIvb9LBIYMBfemhx49dYX1P652vgoiVTrDUKJHT3FFZ2ypbZCRoC4h5TIpzeuYoEI/ZNMxmDtq6b1ojAQitexrAJZGiskJMRCii48cYLo9LRQZAurysxUi/Ur3p5mQvyxeH5JgwIyZFgysd8dL6JZKJxCv71EdzbAd2op72Kc="
