language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
script: "./build.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gfI4KTCBUJ6lzK4KN1/GPqnQngq5I1+cSHBQ3Onmr5jiu363cE2bT+WMNPr1lnLdJe89/vNh0uFhug24PHG+K2BMdxneD3FIKwEPsqSE4WW0hWce22RoGKTn/b1v11tNXi2BReI4zpbliAuSaRtM+SKBceqvii1P4EV1n3BWv8lV6YhYKrcMqiz+H5QHqmfY7pkahdCet9+L4zm1NkFw80XLjoAmbOGh97IWOKNT5803tqkbFYg22iiS7ikexntNfWOVBYvwL/KHJUsbNPVjwEEBbZfFHeZKwnDXsgqCgHbX25f9SFUOD9FQoKCnnioUfPNyLQn+Dk2mK1L+JE/IBCqDY7eKe9JulX3x1yVAy56PPgWslmiCMLaih0zCLv/3r0OoC+zV/1vE2X+VbvhRtSdCG4qJ0GqCqmAQlgLaDnDG0X5hnl2MZ2OpmBZfsnmu56wtf4svIp4drTCuab5a+GbrgSWE9rEihGO8AxUAIQkv50SRlhZCo+TR2pMgokHeOA4YG72b5yK6W5oRx0F3s2hlzwFwmTeYlU1VCq0nlsL79JWfjQL1JgjprvpcCGlYKuDL6vY+BZQl4x0z2+0dw/j1H7xGJFVs6Rvj92tNZs0KxoXU39rqQS89yYZ4hlXCzulR2H8SiZpYzCDLGtP7BSjDrq6sC8uL/1AWNQZyh1k=
  file:
  - target/Forest.love
  - target/Forest-win.zip
  - target/Forest-web.zip
  on:
    tags: true
    all_branches: true
after_success:
  - "[[ -n $TRAVIS_TAG ]] && ./build.sh deploy premek/forest"
env:
  global:
    secure: LLfq9nWX+LfDVQWH3q0T0Kwvuk2bCKCA4lYEkmrr/UaAmh29DM9C7yrwnXcvhw3Lz5RjTugnjzEJWDkDzJfRfvEmQuEFcE/UCPkAreXeO0z8n6pd62ip6S43IzE2qRsuvZdcwiHCEMHSwb+mdvz8HgoJ/p90Le8OYOr5ikMou5HhLMvI+cM10G5vRDFNZ+QzbFTiiaPox8y2a4RjcmzJV4JFnLtIhNmdseJJjGW5+zL4mDBH4dxRISqFl8VePnea/SZv0htekwovY577mrcYYF1bnPnKzlk56Vaw61yJGVWvuo4jiF6kIjGWBeTAMcVGmQxzzpr+zwpRZ9flVxsh26RxvN0zaVL2TytCP+mDCAxLUrVJjAfd/3QlE1bo6GGY9FAnC8/xg6SO9ju0bEwweQBTukiHcZoYwIW+2xSF1zqi0gbANgL8epLjdBmhZpKX0uTlOZfNtvJBDaT5X8djZYsB5s3p7vdn5VGSGNUZ0BP623/4gdzzAhSY+slmN0wsFaJajhKNWwZQFPGcWRplXyPM8m7KgbZU+0qA358l/Ks7ACupulnLp1px7JlnfD3t5HvST+g6kYWtk2QL54No9Nyv7m5IxnBbY1B6Iu7LzJzdo69GoWh46B9oRC8kYdQmDiqkrjT+d8PITd3RyAPgN+bQI7L3svNBdPE63BCe+Ec=
