language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - python2.7
script: "./build.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: gfI4KTCBUJ6lzK4KN1/GPqnQngq5I1+cSHBQ3Onmr5jiu363cE2bT+WMNPr1lnLdJe89/vNh0uFhug24PHG+K2BMdxneD3FIKwEPsqSE4WW0hWce22RoGKTn/b1v11tNXi2BReI4zpbliAuSaRtM+SKBceqvii1P4EV1n3BWv8lV6YhYKrcMqiz+H5QHqmfY7pkahdCet9+L4zm1NkFw80XLjoAmbOGh97IWOKNT5803tqkbFYg22iiS7ikexntNfWOVBYvwL/KHJUsbNPVjwEEBbZfFHeZKwnDXsgqCgHbX25f9SFUOD9FQoKCnnioUfPNyLQn+Dk2mK1L+JE/IBCqDY7eKe9JulX3x1yVAy56PPgWslmiCMLaih0zCLv/3r0OoC+zV/1vE2X+VbvhRtSdCG4qJ0GqCqmAQlgLaDnDG0X5hnl2MZ2OpmBZfsnmu56wtf4svIp4drTCuab5a+GbrgSWE9rEihGO8AxUAIQkv50SRlhZCo+TR2pMgokHeOA4YG72b5yK6W5oRx0F3s2hlzwFwmTeYlU1VCq0nlsL79JWfjQL1JgjprvpcCGlYKuDL6vY+BZQl4x0z2+0dw/j1H7xGJFVs6Rvj92tNZs0KxoXU39rqQS89yYZ4hlXCzulR2H8SiZpYzCDLGtP7BSjDrq6sC8uL/1AWNQZyh1k=
  file:
  - target/Forest.love
  - target/Forest-win.zip
  - target/Forest-web.zip
  on:
    tags: true
    all_branches: true
